# Generated by Django 2.2.1 on 2019-05-25 00:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PatientID', models.AutoField(primary_key=True, serialize=False)),
                ('GivenName', models.CharField(max_length=100)),
                ('MiddleName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Extention', models.CharField(max_length=5)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(max_length=12)),
                ('StreetAdd', models.CharField(max_length=255)),
                ('BrgyAdd', models.CharField(max_length=255)),
                ('CityAdd', models.CharField(max_length=255)),
                ('Region', models.CharField(max_length=27)),
                ('ContactPerson', models.CharField(max_length=50)),
                ('ContactNumber', models.IntegerField(max_length=11)),
                ('DateCreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
