# Generated by Django 2.2.1 on 2019-05-26 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190525_1330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
