# Generated by Django 2.2.1 on 2019-05-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Extention',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
