# Generated by Django 2.2.1 on 2019-05-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20190526_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Extention',
            field=models.TextField(max_length=5, null=True),
        ),
    ]
